profile: none

initialization:
  mode: warmstart
  resume:
    checkpoint_path: null
    vecnormalize_path: null
    target_total_timesteps: null
    additional_timesteps: false
  warmstart:
    params_path: examples/resnet_example.zip
    vecnormalize_path: null
  vecnormalize_path: null

env:
  mode: v1
  height: 8
  width: 8
  num_robots: 2
  include_noop: false
  step_penalty: -0.01
  goal_reward: 1.0
  noop_penalty: -0.01
  max_steps: 20
  seed: 0
  ensure_solvable: false
  solver_max_depth: 30
  solver_max_nodes: 20000
  obs_mode: image

algo:
  algo: ppo
  timesteps: 1000000
  n_envs: 8
  n_steps: 256
  batch_size: 128
  n_epochs: 4
  lr: 0.00002
  lr_end: 0.00002
  lr_schedule: linear
  gamma: 0.99
  clip_range: 0.2
  clip_end: 0.1
  clip_schedule: none
  gae_lambda: 0.95
  vf_coef: 0.5
  max_grad_norm: 0.5
  ent_coef: 0.001
  normalize_advantage: true
  device: auto

model:
  type: resnet
  params:
    features_dim: 32
    conv_channels: 32
    lstm_channels: 64
    lstm_layers: 2
    lstm_repeats: 1

curriculum:
  enabled: true
  use_bank: true
  bank_dir: artifacts/puzzle_bank
  config: configs/curriculum_config_default.json
  initial_level: 0
  success_threshold: 0.9
  min_episodes: 60
  window_size: 100
  check_freq: 50
  verbose: true

eval:
  eval_freq: 1000
  eval_episodes: 100
  fixedset: null
  solver_cache: eval/solver_cache.json
  traj_record_freq: 2000
  traj_record_episodes: 10

monitoring:
  log_dir: artifacts/runs/ppo
  save_path: artifacts/checkpoints/ppo_model_tmp22
  save_freq: 5000
  tensorboard: false
  wandb: true
  wandb_entity: null
  wandb_project: null
  wandb_run_name: null
  wandb_tags: null
