algo: ppo
bank_dir: ./puzzle_bank
batch_size: 128
clip_end: 0.1
clip_range: 0.2
clip_schedule: none
init_mode: warmstart
resume_additional_timesteps: false
resume_checkpoint_path: null
resume_target_total_timesteps: null
resume_vecnormalize_path: null
vecnorm_load_path: null
warmstart_params_path: examples/resnet_example.zip
warmstart_vecnormalize_path: null
conv_channels: 32
convlstm: false
curriculum: true
curriculum_check_freq: 50
curriculum_config: configs/curriculum_config_default.json
curriculum_initial_level: 0
curriculum_min_episodes: 60
curriculum_success_threshold: 0.9
curriculum_verbose: true
curriculum_window_size: 100
device: auto
drc: false
enable_profiling: false
ensure_solvable: false
ent_coef: 0.001
env_mode: v1
eval_episodes: 100
eval_fixedset: null
eval_freq: 1000
features_dim: 32
gae_lambda: 0.95
gamma: 0.99
goal_reward: 1.0
height: 8
include_noop: false
load_path: null
log_dir: runs/ppo
lr: 0.00002
lr_end: 0.00002
lr_schedule: linear
lstm_channels: 64
lstm_layers: 2
lstm_repeats: 1
max_grad_norm: 0.5
max_steps: 20
monitor_tensorboard: false
monitor_wandb: true
n_envs: 8
n_epochs: 4
n_steps: 256
noop_penalty: -0.01
normalize_advantage: true
num_robots: 2
obs_mode: image
profile: none
profiling_report: profiling_report.json
profiling_summary_freq: 10000
resnet: true
save_freq: 5000
save_path: checkpoints/ppo_model_tmp22
seed: 0
small_cnn: false
solver_cache: eval/solver_cache.json
solver_max_depth: 30
solver_max_nodes: 20000
step_penalty: -0.01
timesteps: 1000000
traj_record_episodes: 10
traj_record_freq: 2000
use_bank_curriculum: true
vecnorm: false
vecnorm_clip_obs: 10.0
vecnorm_clip_reward: 10.0
vecnorm_norm_obs: true
vecnorm_norm_reward: false
vf_coef: 0.5
wandb_entity: null
wandb_project: null
wandb_run_name: null
wandb_tags: null
width: 8
